
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Chart.Name}}-data
  namespace: {{.Values.namespace}}
spec:
  volumeName: {{.Chart.Name}}-data
  accessModes:
    - {{ index .Values.todoapp.pvc.accessModes 0 }}
  resources:
    requests:
      storage: {{.Values.todoapp.pvc.resources.requests.storage }}