apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.todoapp.hpa.minReplicas }}
  strategy:
    type: {{ .Values.todoapp.strategy.type }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Values.todoapp.serviceAccountName }}
      containers:
        - name: todoapp-container
          image: "{{ .Values.todoapp.image.repository }}:{{ .Values.todoapp.image.version }}"
          resources:
            limits:
              cpu: {{ .Values.todoapp.resources.limits.cpu | quote }}
              memory: {{ .Values.todoapp.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.todoapp.resources.requests.cpu | quote }}
              memory: {{ .Values.todoapp.resources.requests.memory | quote }}
          # Динамический маппинг переменных окружения из env_secrets через range
          env:
            {{- range .Values.todoapp.env_secrets }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Chart.Name }}-secret
                  key: {{ .valueFrom.secretKeyRef.key }}
            {{- end }}
          volumeMounts:
            - name: todoapp-storage
              mountPath: /app/data
      volumes:
        - name: todoapp-storage
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pvc
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  {{- range .Values.todoapp.nodeaffinity }}
                  - key: {{ .key }}
                    operator: {{ .operator }}
                    values:
                      {{- toYaml .values | nindent 22 }}
                  {{- end }}