apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range $key, $val := .Values.todoapp.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}